name: roboshop
services:
   mongodb:
     build: ./mongodb
     image: sravani3093/monogodb:v1
     container_name: mongodb
   catalogue:
      build: ./catalogue
      image: sravani3093/catalogue:v1
      container_name: catalogue
      depends_on:
      - mongodb
   frontend:
      build: ./frontend
      image: sravani3093/frontend:v1
      container_name: frontend
      ports:
      - "80:80"
      depends_on:
      - catalogue
      - user
      - cart
   user:
      build: ./user
      image: sravani3093/user:v1
      container_name: user
      environment:
         MONGO: true
         REDIS_URL: 'redis://redis:6379'
         MONGO_URL: "mongodb://mongodb:27017/users"
      depends_on:
      - redis
      - mongodb
   redis:
       build: ./redis
       image: sravani3093/redis:v1
       container_name: redis
   cart:
      build: ./cart
      image: sravani3093/cart:v1
      container_name: cart
      environment:
         REDIS_HOST: redis
         CATALOGUE_HOST: catalogue
         CATALOGUE_PORT: 8080
      depends_on:
      - redis
      - catalogue
   mysql:
       build: ./mysql
       image: sravani3093/mysql:v1
       container_name: mysql
       command: --mysql-native-password=ON --innodb-lock_wait_timeout=120
       environment:
        MYSQL_ROOT_PASSWORD: "RoboShop@1"
   shipping:
        build: ./shipping
        image: sravani3093/shipping:v1
        container_name: shipping
        environment:
          CART_ENDPOINT: cart:8080
          DB_HOST: mysql
        depends_on:
        - mysql
        - cart


networks:   
   default: 
     name: roboshop
     driver: bridge
     external: false  